language: mininmal
script: echo no tests
deploy:
  provider: s3
  access_key_id: "$access_key_id"
  secret_access_key: "$secret_access_key"
  bucket: hidden.computer
  region: us-east-2
  skip_cleanup: true
  acl: public_read
  local_dir: public
  on:
    branch: master
env:
  global:
  - secure: MCFFur2EkGinrHqP7CE5ACLYaXagZZTJbbkoTLAVb/fyrI9ZJNlVnBWlmT4aKoW6ug2dW6UnWP+bay0TRnHYXMq81yQfIJeNiEDrTeuuawVUMMvWKapSItrojh9iy6onljWQbE9wXzzJkF0O0wek1AfiB9tY7RidegqqrJeJ6ael0khVKcQBvJTwxlG9QD1pqkSfVeiwgk945YlM4ECU1u6aiedQX0u/o5qltznIhqoY2DiB7ls0kr1zK48thSspsMdsBJb2qTJSmnvisMe4yq8bBjsPjaFn+b3CafwzMBuXj+hs6rHDoncrj/C0utrc2NDrhfUROBmP2iluqXxRxau3dyuW0kAhZE+uqJohDXe5WL79XU1MS6YPRKkYmP6h5YXn+4h78eNPWastA+2OLl0BSzsv21PM16yF6mo1+8DMrFieut9kJhrj58kDLFkA1pkrKlbcJYTFKtIR2tQa/ZGQb+34PvSilalZ4gtSha26ETVW/QIwCmEdSeCdYOMwBeL2Swx/BWImNFaSZ/AEmP4c+WBkVqdixaNeThk/aB0rXAKvOQ+xEoCm6qwwIcT7dsMPp2+JHIFPHwFh/1Dj0C2/6/Yil9JaEPiYzvxyNWvJ+RfGZpkMTvVo94KKhNiJUb9SmwFE0NzANQfl8Of4SQBM714WeK+hSIC9zJ7LdmA=
  - secure: BIJi6GC1kbdz1Syd3N7p4ZpOcAEykH2P+KBWf908g7YHs+fUWku1z4+n7TBTTFzT3QgW5t9wWk2x4DOx9+RzZi43Q12U4gOxFPY7YQcAIqgtu/pychzDiw6xCSMN2O7r0q4QCRzGJA4ueNLfj20JtdS2jiCVyBvicqsMUkWswN3w1CJirjBaTbL1MO5NxROYpJXnclDY7+IW3Vyv0CryMUpvwvWWQsl9nI/xAL6k44IZIsHaW1+IAS4daL8SaVMWoYX90xJrgICKi52W/y1tx04QISEcnLak/1yS1Qe+6+oop5YKEeDeJ/lYDQTylrAkaTX43b5N6kx7Ur4PVNSGB+txhJfeYSetlYCQeV4UqFIDo16xlWQwjLBcw72zkDX/X41X7vc8wW7Gns1HQeLlvqK+vvfHM2x9UYcRM6NtIOFs3/cA3ypg7LespYIhR44W9IwmNDwPei2ZB1LmWclkDexQke+pT+HJEc402FvfFlCbDtF9RnRMjS8wFrgL7NE0zhsGm+h4Nq/CGDtwpMdrltWlODIBZIsXU5DUxslSR2hY/Niy9YUjp4jr93pgsIet1BNG4vQwoWBz+7uuIczwdjUgROX1SnYbYVjPemUftJvAjcG3l+zFemo39UkhpQZVe/eniwxHZoxG7VvszP91PFkIWurlaNlh2cJATVWSUzg=
