language: node_js
node_js:
- lts/*
deploy:
  provider: elasticbeanstalk
  access_key_id: "$access_key_id"
  secret_access_key: "$secret_access_key"
  region: us-east-1
  app: hiddencomputer
  env: hiddencomputer
  bucket_name: elasticbeanstalk-us-east-1-197628141427
env:
  global:
  - secure: idFqXGXo4o5sXBA3iddU7su7c5pW4XQU4Bmd20X1NhP4f3OOk3tfxiT031s/Em3ONsvRIQiYcnAfssixL2mEHlpC68ezRClCUXuhS61TKWl5WUH5cOyP0nW7+xP4Ndj9QOn91TlpWsGNJbUBoLXDf9VerGqngHLXYbjYlWwPr9SzJn2vj3oHGO9uKcPRbtUdmVk6OHBs0f3rl5OWZq0wyGVtK5OETRFLInbbq9LMzEm9Q1dh0cdCue67WyHtCjEwjN6bndOReQIFGuzXUepH8EW4loCg/clueEOEgCXvMddj7WqOE+1Vji0uZqoEMSTC/3gN2sRshfFvOw6bAv8vIfgBmlrI3/6bzfh7Zm05YsEvqE6l8dICZtlZA2R0U0KjH3SmLq4k5V6L+MG1jvPGe9sX//Ys3QP+aP6b5ZzM9Hj54OXS11NFsLR3ci4fYf8tnAvZrDvjJGrAC553MBj1VFGifXwctw8rebvSRZ+s1l+V8mvKQgTIMYgUsvDvXV7o4sNoiFJwBVG+Wz+jNtJCnkmj1DjF/addo4K3KUxVGaBVPw237V9lh1oje1gxcbfw4Rzl5BKUDfVtAnQ198WoFf4hd8T27x00ekA5MEqH0weq2Pteed+3QI9g+TF6xrleT2r2gr/0aSzZqNR7X+yNk97iVbFb1RZurKch4qqFclA=
  - secure: AN0wDSiGVXcy4bQCHODkRkvBMNhepWqFJhADWI+YQv4/qI/wQZRLn9IYLTfnB4jJY4tJXpdQmCzaknqKlFL5focjBz3VLN/18w0G68e1ocYfsN+t8DDSd/YKXiA3K7870PSHmtvU5N7OliHAU4xGVbBt9pq2r8MpT7DE/dTjoac3pmSrmYxaN9vzNMKarEa0VLBME4agYLFqNUpVXTTF1V5XbDr3VcdazjuXu5oGH8CsPdgr9H+StA+Tl03oUjeyXJ2oNCnbxCdbxX2xfM7m6HPhVOqxXVHZt+s7aGdZ2pSPG1h3WJ4IlMLhzZNe9IRbPWFXf/z7kQRTr0RALT66Qwlbjtv8DaYLUcKfCysjKMDobMYUFSkf6rlh6MVsqMg2rMjFwZ2rZHH1orKydF1dHsjYn2Fdz4bKZB+lhWxy5dignpzUxtr3sj1SWnPMH3S0b6C9wTuq4I+wPi4eRuztV1cnGQRT/Ws1ckKXeveh9p/xHWselNIQDGSaqkn8UyKr1i6L1W1eozyT0UoVVGMsqtqonUbRjbMUz4SngERv0cVFu/Igreb3eEHS6xDS/F5wkwDcnIuT3wuXs9UfXx1nJyXir8QXoCY2PdfQXG/EPuWPacyx2MgI23KWL9+qPoVllPVHI6dQPyHLEyS/V64osZ87izT1Oo/y2gNdnFUEyCw=
