version: '2'
services:
    site:
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/init-nginx.conf:/init-nginx.conf
            - ./nginx/nginx.conf:/next-nginx.conf
            - ./site/static:/usr/share/nginx/html:rw
    ipfs:
        image: ipfs/go-ipfs
        ports:
            - "8080:8080"
